"""CampusIQ M3.1 — campus registry / IFC space extraction tests.

Read-only w.r.t. source data. Validates the canonical CampusIQ
campus foundation generated by `scripts/extract_ifc_spaces.py`.
"""

import hashlib
import json
import os
import sys

import pytest

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(BASE_DIR, "scripts"))

import extract_ifc_spaces as ext  # noqa: E402
import investigate_sensor_ifc_mapping as source  # noqa: E402

IFC_PATH = os.path.join(BASE_DIR, "DS3_TalTech_V4.ifc")
IFC_SHA256 = "05919eee0701b955d3d08501c4889c879d9c486e2389a6a1a5cdaad32a5d10ba"
IFC_SIZE = 38_728_810

SPACE_KEYS = {
    "space_id", "building_id", "storey_id", "ifc_global_id", "ifc_name",
    "ifc_long_name", "ifc_tag", "area_m2", "volume_m3", "height_m",
    "occupiable", "capacity", "geometry_ref", "bim_properties",
}
STOREY_KEYS = {"id", "building_id", "name", "elevation", "ifc_global_id",
               "space_count"}


def _load(name: str):
    with open(os.path.join(source.OUTPUT_DIR, name), encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def reg():
    return _load("campus_registry.json")


@pytest.fixture(scope="module")
def spaces_file():
    return _load("spaces.json")


@pytest.fixture(scope="module")
def extracted():
    """A fresh in-memory extraction (independent of the on-disk outputs)."""
    return ext.build_outputs()


# ---------------------------------------------------------------------------
# Raw data preserved
# ---------------------------------------------------------------------------
def test_raw_ifc_untouched():
    assert os.path.getsize(IFC_PATH) == IFC_SIZE
    with open(IFC_PATH, "rb") as f:
        assert hashlib.sha256(f.read()).hexdigest() == IFC_SHA256


# ---------------------------------------------------------------------------
# 1. exactly 115 IfcSpace records
# ---------------------------------------------------------------------------
def test_exactly_115_spaces_extracted(reg, spaces_file, extracted):
    assert len(reg["spaces"]) == 115
    assert len(spaces_file["spaces"]) == 115
    assert len(extracted["spaces"]) == 115
    assert extracted["metadata"]["ifc_schema"] == "IFC4"


# ---------------------------------------------------------------------------
# 2. unique stable space_ids
# ---------------------------------------------------------------------------
def test_unique_stable_space_ids(reg):
    ids = [s["space_id"] for s in reg["spaces"]]
    assert len(ids) == 115
    assert len(set(ids)) == 115
    for s in reg["spaces"]:
        assert s["space_id"].startswith("space_")
    assert all(s["space_id"] == f"space_{s['ifc_global_id']}" for s in reg["spaces"])


# ---------------------------------------------------------------------------
# 3 & 4. GlobalIds present / unique
# ---------------------------------------------------------------------------
def test_every_space_has_ifc_global_id(reg):
    gids = [s["ifc_global_id"] for s in reg["spaces"]]
    assert all(g for g in gids)
    assert len(set(gids)) == 115
    buildings = [b["ifc_global_id"] for b in reg["buildings"]]
    storeys = [st["ifc_global_id"] for st in reg["storeys"]]
    assert all(buildings)
    assert all(storeys)
    assert len(set(buildings)) == len(buildings)
    assert len(set(storeys)) == len(storeys)


# ---------------------------------------------------------------------------
# 5. storey relationships valid
# ---------------------------------------------------------------------------
def test_storey_relationships_valid(reg):
    st_ids = {st["id"] for st in reg["storeys"]}
    b_ids = {b["id"] for b in reg["buildings"]}
    for s in reg["spaces"]:
        assert s["storey_id"] in st_ids
        assert s["building_id"] in b_ids
    for st in reg["storeys"]:
        assert st["building_id"] in b_ids

    counts = {st["name"]: st["space_count"] for st in reg["storeys"]}
    assert counts == {"+Kelder": 44, "1. korrus": 29, "2. korrus": 18,
                      "3. korrus": 24, "Katus": 0}
    assert len(reg["storeys"]) == 5
    building = reg["buildings"][0]
    assert building["space_count"] == 115
    assert len(building["storey_ids"]) == 5
    assert sum(st["space_count"] for st in reg["storeys"]) == 115


# ---------------------------------------------------------------------------
# 6. area / volume / height numeric where available
# ---------------------------------------------------------------------------
def test_area_volume_height_numeric(reg):
    numeric = 0
    for s in reg["spaces"]:
        for key in ("area_m2", "volume_m3", "height_m"):
            v = s[key]
            assert v is None or (isinstance(v, float) and v > 0), (key, v)
        assert s["occupiable"] in (True, False, None)
        if s["capacity"] is not None:
            assert isinstance(s["capacity"], float)
            numeric += 1
        if s["geometry_ref"] is not None:
            assert s["geometry_ref"].startswith(f"{s['ifc_global_id']}#")
    # all 115 spaces carry numeric areas/volumes in this export
    assert all(isinstance(s["area_m2"], float) for s in reg["spaces"])
    assert all(isinstance(s["volume_m3"], float) for s in reg["spaces"])
    assert all(isinstance(s["height_m"], float) for s in reg["spaces"])
    assert numeric == 115


# ---------------------------------------------------------------------------
# BIM properties preserved
# ---------------------------------------------------------------------------
def test_bim_properties_preserved(reg):
    for s in reg["spaces"]:
        bim = s["bim_properties"]
        assert isinstance(bim, dict) and bim
        assert "Dimensions.Area" in bim
        assert "Energy Analysis.Occupiable" in bim
        assert "Pset_SpaceCommon.Reference" in bim
        qty = s["quantities"]
        assert isinstance(qty, dict) and qty
        assert "Qto_SpaceBaseQuantities.NetVolume" in qty


# ---------------------------------------------------------------------------
# 11. deterministic space IDs across extractions
# ---------------------------------------------------------------------------
def test_deterministic_space_ids(extracted):
    second = ext.build_outputs()
    a = [(s["space_id"], s) for s in extracted["spaces"]]
    b = [(s["space_id"], s) for s in second["spaces"]]
    assert a == b
    assert [st["id"] for st in extracted["storeys"]] == \
           [st["id"] for st in second["storeys"]]
    assert [bld["id"] for bld in extracted["buildings"]] == \
           [bld["id"] for bld in second["buildings"]]


# ---------------------------------------------------------------------------
# 12. JSON structure validation
# ---------------------------------------------------------------------------
def test_json_structure(reg, spaces_file):
    assert {"campus", "buildings", "storeys", "spaces", "metadata"} <= set(reg)
    c = reg["campus"]
    assert {"id", "name", "building_count", "storey_count", "space_count"} <= set(c)
    assert reg["campus"]["space_count"] == 115
    for b in reg["buildings"]:
        assert {"id", "campus_id", "name", "ifc_global_id"} <= set(b)
    for st in reg["storeys"]:
        assert STOREY_KEYS <= set(st)
    for s in reg["spaces"]:
        assert SPACE_KEYS <= set(s)
        assert s["ifc_global_id"]  # global ids never empty
    assert set(spaces_file.keys()) == {"spaces"}
    assert spaces_file["spaces"] == reg["spaces"]


def test_no_fabricated_sensor_links_in_spaces(reg):
    """Spaces carry no sensor references (nothing invented at foundation time)."""
    for s in reg["spaces"]:
        assert "sensor" not in {k.lower() for k in s["bim_properties"]}


# ---------------------------------------------------------------------------
# M1 artefacts remain intact (reuse check)
# ---------------------------------------------------------------------------
def test_m1_spaces_reference_still_consistent():
    rep = _load("sensor_ifc_mapping.json")
    assert len(rep["ifc_spaces_reference"]) == 115
    fresh = ext.build_outputs()
    fresh_gids = [s["ifc_global_id"] for s in fresh["spaces"]]
    m1_gids = [s["ifc_global_id"] for s in rep["ifc_spaces_reference"]]
    assert sorted(fresh_gids) == sorted(m1_gids)