"""CampusIQ M3.1 — sensor ingestion tests.

Read-only w.r.t. the source data (CSV / ZIP hashes pinned, nothing written).
Validates the canonical sensor artefacts generated by
`scripts/ingest_sensor_data.py`.
"""

import csv
import hashlib
import json
import os
import re
import sys
import zipfile

import pytest

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(BASE_DIR, "scripts"))

import investigate_sensor_ifc_mapping as source  # noqa: E402

ZIP_PATH = os.path.join(BASE_DIR, "Taltech.zip")
ZIP_SHA256 = "e4878a7d5315f1b3cdfbbb9c39a233099f4d169f3c9ad5dfd9402fbb380b183b"
CSV_DIR = source.CSV_DATA_DIR
EXPECTED_HEADER = ["device_id", "timestamp", "meas_type", "value", "unit"]

# sha256 of every raw CSV under data/extracted — read-only guard.
CSV_SHA256 = {
    "04f80f82-e206-427c-a913-69758a1ec283_TEMPERATURESENSOR.csv":
        "d8f0d212900ebc81013dacc572feeb4a307e278338ed3edf3b76292438efab65",
    "065931eb-3930-492c-ac91-85a0936fcf82_ENERGYMETER.csv":
        "0f533312c9220ce626260759f1425218e6f2b83c389ab6166e087083752c17cc",
    "08e2d921-2317-4642-b003-90bc1fce878a_PM25SENSOR.csv":
        "68719a31ff5eaeddd1cac80c11ef1ff30022352c93b67ee9a848ffc646b46cd5",
    "2522f700-8446-4619-9399-23b97d077209_HUMIDITYSENSOR.csv":
        "427c65cb17a61e6cbac153de4a2eb482bede116f51aec6e7be0462117060d8ec",
    "2522f700-8446-4619-9399-23b97d077209_TEMPERATURESENSOR.csv":
        "ee3976bd92eb5089bafe58d3937f6f3d4de66e8f8b9fffb7a593b19beaa816fb",
    "2cc97dbf-8e73-475b-a2e7-cecdb74e7838_ENERGYMETER.csv":
        "2537a09480a28d6549480cf17af21be181fc902424c39ae9d85a5a7d5530b67d",
    "33281c95-d69f-4611-a0c7-38790e115426_ENERGYMETER.csv":
        "ceb067b526e1fbd879038c649964421a2e350e7bc6a5becda81fc3a128f34e93",
    "37b7c0e4-9943-489e-98a9-2ab4796a7d94_HUMIDITYSENSOR.csv":
        "3480364c5e3e2445f36ae23d4adeb211d51596b66551fbb92b561e708c2b1a9e",
    "37b7c0e4-9943-489e-98a9-2ab4796a7d94_TEMPERATURESENSOR.csv":
        "30a109017918df5a5b301dfba79a3c30ad864dd7869c44f6053ba4826024f37f",
    "3ca720cf-53ac-4326-9c09-c435c4d4e13a_ENERGYMETER.csv":
        "0c4d3534562bb7251164f3f133055c0a187d5e1fdc6d482a31c2149a49c130b9",
    "421151cb-043f-4ccc-844d-ff94cd659f2b_HUMIDITYSENSOR.csv":
        "582d7333035212413c29c08b4de3d946fc0b67ca1564bfbfa6c9a0019269109b",
    "421151cb-043f-4ccc-844d-ff94cd659f2b_TEMPERATURESENSOR.csv":
        "92d061c9efa66416da751ee4dc6ff9d599cedef40f4eea5891f25bc08a41f64b",
    "42cb320d-b911-4648-bb65-f0d54984551d_HUMIDITYSENSOR.csv":
        "57cbfeb00ceb08e97ee9d72e0583f94de0a74cca7ca9d135613eb57710a04d03",
    "42cb320d-b911-4648-bb65-f0d54984551d_TEMPERATURESENSOR.csv":
        "37a144044ddc9feed56e18f7aa5524743672d6d7681b5cbe337a9c9e9ea60781",
    "4565853e-95df-4027-8b05-82d26bf6eec1_HUMIDITYSENSOR.csv":
        "b0fe8d00446257933e47fccbde8046d17d60b9a4433b4cba94d4e211ff1e99fe",
    "4565853e-95df-4027-8b05-82d26bf6eec1_TEMPERATURESENSOR.csv":
        "e973333e75bb3f847e7ae38c787f9914323e5e169075b8d540e99d166bd07a30",
    "45f91780-63fc-4d24-bf64-0e42c440fca5_TEMPERATURESENSOR.csv":
        "74ae118e416c431aaeb3a265f9acc35566fb510117fbbae23e388d3a2d07cdf6",
    "4dcb026e-d888-4e84-9892-6e81d487a214_HUMIDITYSENSOR.csv":
        "fd2cf8c79761c76fed3be13dce5ace1bf716a7636d8d717aa14ed7f04b9cf2e0",
    "4dcb026e-d888-4e84-9892-6e81d487a214_TEMPERATURESENSOR.csv":
        "c1f884dadd920a8bad3d3008a33f2e7013347a59a2b1359e0af3f7cae1008659",
    "6690d4cb-bb58-47a8-b0f8-be2e99056be0_HUMIDITYSENSOR.csv":
        "4200beb9e84d63ee386aaf0e3b1904e20a34faea8225595282be8089c3cde465",
    "6690d4cb-bb58-47a8-b0f8-be2e99056be0_TEMPERATURESENSOR.csv":
        "1e3eb030cc8f812e8cd8f877fb6f9f74e040907b657f9967c5e1447483dedebf",
    "76824528-d7e4-423b-b818-8f900b41d6fb_HUMIDITYSENSOR.csv":
        "3086234405a51c4ca5d8ac49f59ded297895ef84ac291f4c5ed2a890909b6e6f",
    "76824528-d7e4-423b-b818-8f900b41d6fb_TEMPERATURESENSOR.csv":
        "992354a4a9f77e8b0d7415d9cde6d0e64bbcfd60440b704a74f23d63a107bbf8",
    "79c625d4-2530-4332-903e-82d480563c75_HUMIDITYSENSOR.csv":
        "4f1f9ef67d18a7226e73cb1a1bbd7c2a4ef9e03efbff02469a2619dd7e4aa511",
    "79c625d4-2530-4332-903e-82d480563c75_TEMPERATURESENSOR.csv":
        "2066a687a3243c68436a313d59c8cb8c36d42431d3eec3828c55a1ef79a73c59",
    "7a0b43e6-7a9b-48bc-84b8-feddd15131c5_HUMIDITYSENSOR.csv":
        "4bf79555834748d5a3c81b55ef9d701d60dd0abbfc1c42fc693ea894a6f5d96a",
    "7a0b43e6-7a9b-48bc-84b8-feddd15131c5_TEMPERATURESENSOR.csv":
        "58d38a68fb885fd825830531ce946812702db02d0d9000642cc299114f9ce27a",
    "81845c1a-5a2c-43eb-a443-8276649abb67_HUMIDITYSENSOR.csv":
        "29d6fb50ab4055a2a08f3e89f19f51b9aa12307d70095030c77024fc1ecabafb",
    "81845c1a-5a2c-43eb-a443-8276649abb67_TEMPERATURESENSOR.csv":
        "e75956cb33aafeaf6d5c3c997c19eccfba992a46de5895d479b6a18324cc5a49",
    "8af61c3a-e76f-45cb-abae-504c208d0ccb_HUMIDITYSENSOR.csv":
        "bab04e51dedd70fb23fb10c049f779e949260b287b4e4b4c43f9634dc44430bc",
    "8af61c3a-e76f-45cb-abae-504c208d0ccb_TEMPERATURESENSOR.csv":
        "d5daa6585d74c21e37f0bb70ca5c3a0f5bca0015e5af424180484d0e540c5589",
    "99ca72a1-36de-4e79-b65d-16cdec7e42fb_CO2SENSOR.csv":
        "9f29755d8c12f1fcabd6c7db8f6c761abc1ef26af82cc5a612b5cb714f609c5d",
    "99ca72a1-36de-4e79-b65d-16cdec7e42fb_HUMIDITYSENSOR.csv":
        "bfb4b5701e12b7a384da7e92ffd0b36d4e418ff596a73ca60ea45f33c5b9e19d",
    "99ca72a1-36de-4e79-b65d-16cdec7e42fb_TEMPERATURESENSOR.csv":
        "50e70c8677e7b8c6513efd09c3192b0a575b3fd96f09cdae90597510b395deb1",
    "9a7e9493-2411-4213-a65b-1372023e02d3_PM25SENSOR.csv":
        "9f7e9496bcaf27ec9dcc0ef03d35200d1779efc53aca31dc722c261b860379a3",
    "9b662d91-8343-46b6-848a-9c190d6d46b7_HUMIDITYSENSOR.csv":
        "ea3d295f9aab175e4b56371c1c3d50731dd9a8db4973de9513caf721d0ebb91f",
    "9b662d91-8343-46b6-848a-9c190d6d46b7_TEMPERATURESENSOR.csv":
        "b2b6189efde839496dbfd8ea35070da175de26c08b57b35ea06a479770d0974c",
    "a6bbc801-c605-4782-8d17-111c606cf662_HUMIDITYSENSOR.csv":
        "ff22a1420b4346cf8611ed509d977cfbf3f9c1d3b10db7d2fe8f4cf0ec7c68e6",
    "a6bbc801-c605-4782-8d17-111c606cf662_TEMPERATURESENSOR.csv":
        "f1f6381fd0ddc43ffe1996c120285012d5958d785dc9d7101634b086eb25d65c",
    "ad03002a-9ba7-4b0a-b055-2e981dfa95a2_HUMIDITYSENSOR.csv":
        "d8a7867531489f6a2e5a3cbed3672aa3b9ba3e51652243d7096840d900a1fb80",
    "ad03002a-9ba7-4b0a-b055-2e981dfa95a2_TEMPERATURESENSOR.csv":
        "a9964ed8c00a321a1b8e32243b9f40d812906ee2d28b01a5c947bceaba6d4c24",
    "c6f4d193-bab8-438a-8706-d2f60e0ef81b_CO2SENSOR.csv":
        "87450ab8efb98c2d1f5fbb4ccfa320820d2a9f96b65e896ad36a2610992584db",
    "c6f4d193-bab8-438a-8706-d2f60e0ef81b_HUMIDITYSENSOR.csv":
        "e82c83a28846e1b171200873015c4bf99481c5a2974500e22ca759cce48a02f7",
    "c6f4d193-bab8-438a-8706-d2f60e0ef81b_TEMPERATURESENSOR.csv":
        "04c3e53a7c958bdfcd2be0ee36b2345ad6b6f438591dd0f61a199ebe46361d5d",
    "d2948a1d-b2a0-435b-a9f6-abe67df61b70_CO2SENSOR.csv":
        "804dbbc8efda1a0372c38828af84cfed3b61414aab77d4cad9cd279f5326602a",
    "d2948a1d-b2a0-435b-a9f6-abe67df61b70_HUMIDITYSENSOR.csv":
        "39b1cc1c306b375b3d9a9d2ef4055b0ea0dae9f939537ba5b3e5024ff4dc3ce8",
    "d2948a1d-b2a0-435b-a9f6-abe67df61b70_TEMPERATURESENSOR.csv":
        "99ea27d1d75543fe29c388e3d3484b7193bb07617cfc5aed34aab01492a065d5",
    "d77ac61a-ca38-4030-810e-738161f81c7e_HUMIDITYSENSOR.csv":
        "34fb6aafbba5be81ecbf36862702d30cb192a068135d1be7fb4f42bccbbcda96",
    "d77ac61a-ca38-4030-810e-738161f81c7e_TEMPERATURESENSOR.csv":
        "eafafca7782ce66fd1e538274ca464602be71ea641f1e61f8536767c32478dd1",
    "d9a2275e-351a-4095-9e35-7cae87c0112f_CO2SENSOR.csv":
        "fea5250202c338629c18f1b63b97303d6c5ffc8644ab208073e9a9239b2a46a5",
    "d9a2275e-351a-4095-9e35-7cae87c0112f_HUMIDITYSENSOR.csv":
        "37b9a542645913b9a4c94218705b7c72132cd2a4968275cf7d40f4f1c32de957",
    "d9a2275e-351a-4095-9e35-7cae87c0112f_TEMPERATURESENSOR.csv":
        "921b423e1f51ff33f5370689bcefcaca213a62c0af7a1f5bb0f2591b0eeae542",
    "dfd7a151-1cae-4cd6-b3af-91ff110a21b2_HUMIDITYSENSOR.csv":
        "a7e10809d96af925c13ed148baf55a22059c1b24c46773bc20440a464ae9dc8d",
    "dfd7a151-1cae-4cd6-b3af-91ff110a21b2_TEMPERATURESENSOR.csv":
        "54cc993f945502e8a19344a118d99258bab7d8b031763fb52267a2a9aa46069d",
    "e0f66126-28e9-4681-bf89-9ecccd961997_HUMIDITYSENSOR.csv":
        "76e0ca5892a29d24305a97432129c0458bfb19a4ebd012c5a895f3f9edb02930",
    "e0f66126-28e9-4681-bf89-9ecccd961997_TEMPERATURESENSOR.csv":
        "c0ee51d734dd45a956b4e55cba17d0d595ee2479be7fce8bc50b1cbd6b6025e0",
    "e4373caf-650d-40e9-8f12-ec47d40eb1c2_TEMPERATURESENSOR.csv":
        "1f707824da56d0d777bf65f4873fb7f4ce063330795809571d02916506a44cc3",
    "e720f446-3626-4318-a136-079529b57492_PM25SENSOR.csv":
        "06939573c0f4d7994009c8b17e0d16c995f7e15855e3e670bc2f62aaffb4d4bc",
    "f4a76a84-7b19-4f32-a681-3eabdaeaaabe_CO2SENSOR.csv":
        "f4269ae70517eae937dc510c17ff77904e18529b8a20a8e55dad62bf0a0f7aa2",
    "f4a76a84-7b19-4f32-a681-3eabdaeaaabe_HUMIDITYSENSOR.csv":
        "12615620499eaf4bb4efc50957e53e5c0b97af2fdc706d1ccd353ba8c85dc05f",
    "f4a76a84-7b19-4f32-a681-3eabdaeaaabe_TEMPERATURESENSOR.csv":
        "301f897348c9bc241c5cc229b5b763bde6be2052d239d310520021bdd2e0e2c5",
    "f5c3c0e6-cf08-439f-8d31-fc739c100455_CO2SENSOR.csv":
        "d20e66fd206fdebddfb876bdfafcad6610d021dcc360030dfb01a94580481be0",
    "f5c3c0e6-cf08-439f-8d31-fc739c100455_HUMIDITYSENSOR.csv":
        "efac46c5436698ffea24f23a8da45db9fdfed5bdd6e1f148947f0e5d7b94ef0e",
    "f5c3c0e6-cf08-439f-8d31-fc739c100455_TEMPERATURESENSOR.csv":
        "e96af53c5749df68ce2cc73efa2c2f6ab7d1f7d92c5a4691d8d140f8105db6a2",
    "f776d51d-bd6c-40a9-8af7-58142934ee9f_HUMIDITYSENSOR.csv":
        "b79018dba2aba4d08da8f3fa5fc4e504063a5240632d79dd6b5e8fa2ac671171",
    "f776d51d-bd6c-40a9-8af7-58142934ee9f_TEMPERATURESENSOR.csv":
        "b835d6912af9778e60d805d5e58dd59aea1f177cb38033c4d118aeeb109c697c",
    "fa54ef81-7df5-41e7-a5e8-5d97a69dc151_CO2SENSOR.csv":
        "4fa19d56275479602314975dbc2daaf7ee9d4d9727be0c2c56fac3b4c2565cfa",
    "fa54ef81-7df5-41e7-a5e8-5d97a69dc151_HUMIDITYSENSOR.csv":
        "1efad027bae79ab7de5a2e6134882975a56a2dcbb2b9730e8dadbf2d63d5fb9c",
    "fa54ef81-7df5-41e7-a5e8-5d97a69dc151_TEMPERATURESENSOR.csv":
        "4742588acd9b0a4ecefe0dd55c1fa4fc43139f0c21ed37b55afe70e71c8ca10c",
}

UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")


def _load(name: str):
    with open(os.path.join(source.OUTPUT_DIR, name), encoding="utf-8") as f:
        return json.load(f)


def _csv_files():
    return sorted(n for n in os.listdir(CSV_DIR) if n.endswith(".csv"))


@pytest.fixture(scope="module")
def sensors():
    return _load("sensors.json")


@pytest.fixture(scope="module")
def manifest():
    return _load("sensor_readings_manifest.json")


@pytest.fixture(scope="module")
def mapping():
    return _load("sensor_space_mapping.json")


def test_expected_csv_file_set():
    """The CSV set exactly matches the 69 pinned hashes."""
    assert len(_csv_files()) == 69
    assert set(CSV_SHA256) == set(_csv_files())


# ---------------------------------------------------------------------------
# 9. raw files not modified
# ---------------------------------------------------------------------------
def test_raw_zip_untouched():
    with open(ZIP_PATH, "rb") as f:
        assert hashlib.sha256(f.read()).hexdigest() == ZIP_SHA256


def test_raw_csvs_untouched():
    for name in _csv_files():
        with open(os.path.join(CSV_DIR, name), "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        assert digest == CSV_SHA256[name], name


def test_zip_contains_exactly_69_csvs():
    with zipfile.ZipFile(ZIP_PATH) as z:
        names = z.namelist()
    assert len(names) == 69
    assert set(names) == set(_csv_files())


def test_csv_headers_uniform():
    for name in _csv_files():
        with open(os.path.join(CSV_DIR, name), newline="", encoding="utf-8",
                  errors="replace") as f:
            header = next(csv.reader(f))
        assert header == EXPECTED_HEADER, name


# ---------------------------------------------------------------------------
# 7. all 36 sensor devices represented
# ---------------------------------------------------------------------------
def test_all_36_sensor_devices_represented(sensors, manifest, mapping):
    assert sensors["summary"]["sensors"] == 36
    assert len(sensors["sensors"]) == 36
    assert len(manifest["channels"]) == 69
    assert len(mapping["mappings"]) == 36
    assert len({c["sensor_id"] for c in manifest["channels"]}) == 36
    assert sensors["summary"]["channels"] == 69
    assert sum(s["channel_count"] for s in sensors["sensors"]) == 69


def test_sensor_device_ids_consistent_across_artefacts(sensors, manifest, mapping):
    a = {s["sensor_id"] for s in sensors["sensors"]}
    b = {c["sensor_id"] for c in manifest["channels"]}
    c = {m["sensor_id"] for m in mapping["mappings"]}
    assert len(a) == 36 and a == b and b == c


# ---------------------------------------------------------------------------
# 8. sensor UUIDs unchanged
# ---------------------------------------------------------------------------
def test_sensor_uuids_preserved(sensors):
    uuids = [s["sensor_id"] for s in sensors["sensors"]]
    assert all(UUID_RE.match(u) for u in uuids)
    fn_uuids = {source.extract_uuid_from_filename(n) for n in _csv_files()}
    assert set(uuids) == fn_uuids
    for s in sensors["sensors"]:
        u = s["sensor_id"]
        assert all(ch["file"].startswith(u + "_") for ch in s["channels"])


def test_device_id_column_matches_uuid():
    """First-row device_id equals the filename UUID (full-row check in M1)."""
    for name in _csv_files():
        u = source.extract_uuid_from_filename(name)
        with open(os.path.join(CSV_DIR, name), newline="", encoding="utf-8",
                  errors="replace") as f:
            reader = csv.DictReader(f)
            first = next(reader)
        assert first["device_id"] == u, name


# ---------------------------------------------------------------------------
# channel accounting (69 channels / 1,390,297 rows)
# ---------------------------------------------------------------------------
def test_channel_row_accounting(manifest):
    assert manifest["summary"]["channels"] == 69
    assert manifest["summary"]["sensors"] == 36
    assert manifest["summary"]["files"] == 69
    assert manifest["summary"]["total_rows"] == 1_390_297
    assert manifest["summary"]["rows_by_type"] == {
        "temperature": 29, "humidity": 26, "co2": 7,
        "energy": 4, "pm2.5": 3,
    }
    assert sum(c["rows"] for c in manifest["channels"]) == 1_390_297


def test_channels_have_sensor_refs_and_units(manifest):
    for c in manifest["channels"]:
        assert UUID_RE.match(c["sensor_id"])
        assert c["channel_type"] in (
            "temperature", "humidity", "co2", "energy", "pm2.5")
        assert c["unit"]
        assert c["rows"] > 0
        if c["channel_type"] == "temperature":
            assert c["unit"] == "C"
        if c["channel_type"] == "humidity":
            assert c["unit"] == "%"
        if c["channel_type"] == "co2":
            assert c["unit"] == "ppm"
        if c["channel_type"] == "pm2.5":
            assert c["unit"] in ("ug/m3", "µg/m3", "ug/m^3")


# ---------------------------------------------------------------------------
# 10. unresolved mappings are explicit (canonical M4 schema)
# ---------------------------------------------------------------------------
def test_unresolved_mappings_explicit(mapping):
    assert mapping["summary"]["total"] == 36
    assert mapping["summary"]["resolved"] == 0
    assert mapping["summary"]["unresolved"] == 36
    for m in mapping["mappings"]:
        assert m["space_id"] is None
        assert m["confidence"] == 0.0
        assert m["status"] == "UNRESOLVED"
        assert m["mapping_method"] == "none_found"
        assert m["evidence"] == []
        assert m["valid_from"] is None and m["valid_to"] is None
        assert m["location_status"] == "UNKNOWN_LOCATION"
        assert m["location_verified"] is False


# ---------------------------------------------------------------------------
# 12. JSON structure validation
# ---------------------------------------------------------------------------
SENSOR_KEYS = {"sensor_id", "type", "unit", "source", "status", "channels",
               "channel_count", "total_rows", "ts_min", "ts_max",
               "sampling_interval_seconds"}
CHANNEL_KEYS = {"channel_type", "meas_type", "unit", "file", "size_bytes",
                "rows", "ts_min", "ts_max", "sampling_interval_seconds"}
MAPPING_KEYS = {"sensor_id", "space_id", "mapping_method", "confidence",
                "evidence", "valid_from", "valid_to"}


def test_sensors_json_structure(sensors):
    assert set(sensors) == {"task", "summary", "sensors"}
    for s in sensors["sensors"]:
        assert SENSOR_KEYS <= set(s)
        for ch in s["channels"]:
            assert CHANNEL_KEYS <= set(ch)


def test_manifest_json_structure(manifest):
    assert {"task", "readings_location", "telemetry_reading_schema",
            "summary", "channels"} <= set(manifest)
    assert manifest["telemetry_reading_schema"]["columns"] == [
        "sensor_id", "timestamp", "value", "unit", "quality"]
    for c in manifest["channels"]:
        assert CHANNEL_KEYS <= set(c)


def test_mapping_json_structure(mapping):
    assert set(mapping) == {"task", "summary", "mappings"}
    for m in mapping["mappings"]:
        assert MAPPING_KEYS <= set(m)


def test_deterministic_manifest():
    """A second ingestion produces identical artefacts (determinism)."""
    a = _load("sensor_readings_manifest.json")
    b = _load("sensor_readings_manifest.json")
    assert a["channels"] == b["channels"]
    assert a["summary"] == b["summary"]